name: Docker Image CI

on:
  schedule:
  # each first day of month
  - cron: "0 0 1 * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # github.event.repository.name is empty when not triggered but scheduled (via cron)
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        REPONAME: $(echo ${{env.GITHUB_REPOSITORY}} | cut -d'/' -f2-)
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build . --file Dockerfile --tag ${{REPONAME}}
